import { GetServerSideProps } from "next";
import Head from "next/head";
import { Header, Hero, Modal, Row, SubscriptionPlan } from "src/components";
import { IMovie, Product } from "src/interfaces/app.interface";
import { API_REQUEST } from "src/services/api.service";
import { useInfoStore } from "src/store";

export default function Home({
  trending,
  topRated,
  tvTopRated,
  documentary,
  products,
  subscription,
}: HomeProps): JSX.Element {
  const {modal} = useInfoStore()
  
	if (!subscription.length) return <SubscriptionPlan products={products}  />;

  return (
    <div className={`relative min-h-screen ${modal && '!h-screen overflow-hidden'}`}>
      <Head>
        <title>Home - Abdu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Header />
      <main className="relative pl-4 pb-24 lg :space-y-24 lg:pl-16">
        <Hero trending={trending} />
        <Row title="Top Rated" movies={topRated} />
        <Row title="TV Shou" movies={tvTopRated} isBig={true} />
        <Row title="Documentary" movies={documentary.reverse()} />
        <Row title="Popular" movies={trending} />
      </main>
      {modal && <Modal />}
    </div>
  );
}

export const getServerSideProps: GetServerSideProps<HomeProps> = async ({ req }) => {
	const user_id = req.cookies.user_id;

  if (!user_id) {
		return {
			redirect: { destination: '/auth', permanent: false },
		};
	}

	const [trending, topRated, tvTopRated, documentary, products, subscription] =
		await Promise.all([
			fetch(API_REQUEST.trending).then(res => res.json()),
			fetch(API_REQUEST.top_rated).then(res => res.json()),
			fetch(API_REQUEST.tv_top_rated).then(res => res.json()),
			fetch(API_REQUEST.documentary).then(res => res.json()),
			fetch(API_REQUEST.products_list).then(res => res.json()),
			fetch(`${API_REQUEST.subscription}/${user_id}`).then(res => res.json()),
		]); 
                                                             
  return { 
    props: {
      trending: trending.results,
      topRated: topRated.results,
      tvTopRated: tvTopRated.results,
      documentary: documentary.results,
      products: products.products.data,
      subscription: subscription.subscription.data,
    },
  };
};

interface HomeProps {
  trending: IMovie[];
  topRated: IMovie[];
  tvTopRated: IMovie[];
  documentary: IMovie[];
  products: Product[];
  subscription: string[];
}
